# Generated by Django 3.2.15 on 2022-09-01 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_bookinstance_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
